#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-config
Version  : 1.3.4
Release  : 1
URL      : https://github.com/lightbend/config/archive/v1.3.4.tar.gz
Source0  : https://github.com/lightbend/config/archive/v1.3.4.tar.gz
Source1  : https://repo.maven.apache.org/maven2/com/typesafe/config/1.3.0/config-1.3.0.jar
Source2  : https://repo.maven.apache.org/maven2/com/typesafe/config/1.3.0/config-1.3.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-config-data = %{version}-%{release}
Requires: mvn-config-license = %{version}-%{release}

%description
Configuration library for JVM languages.
[![Maven Central](https://maven-badges.herokuapp.com/maven-central/com.typesafe/config/badge.svg)](https://maven-badges.herokuapp.com/maven-central/com.typesafe/config)
[![Build Status](https://travis-ci.org/lightbend/config.svg?branch=master)](https://travis-ci.org/lightbend/config)

%package data
Summary: data components for the mvn-config package.
Group: Data

%description data
data components for the mvn-config package.


%package license
Summary: license components for the mvn-config package.
Group: Default

%description license
license components for the mvn-config package.


%prep
%setup -q -n config-1.3.4

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-config
cp LICENSE-2.0.txt %{buildroot}/usr/share/package-licenses/mvn-config/LICENSE-2.0.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/typesafe/config/1.3.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/typesafe/config/1.3.0/config-1.3.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/typesafe/config/1.3.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/typesafe/config/1.3.0/config-1.3.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/typesafe/config/1.3.0/config-1.3.0.jar
/usr/share/java/.m2/repository/com/typesafe/config/1.3.0/config-1.3.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-config/LICENSE-2.0.txt
